### PR TITLE
Oct10 bug fixes

### LINKED ISSUE #23: Minor variable change wrt "enabled" flags
In the config implementation on the desktop, both macro and command objects have "enable" flags to determine whether or not the macro or command in question is enabled. Please change this from `enable` to `enabled`.

### LINKED ISSUE #24: Directives pull from wrong attribute.
Please ensure that commands and macros configured via the `UPDATE_CONFIGURATION` message are accessed via the `directive` variable, not the `name` variable, when called upon by the `ROUTE_COMMAND` message.

### LINKED ISSUE #26: Ensure saved command consistency wrt case.
Please save all configured command directives as lowercase characters, or ensure that they can be retrieved using lowercase (even if they're saved as uppercase characters). The dispatcher will be configured to only send lowercase commands.

### PR DESCRIPTION
**Pull request by rj-lee**

### CODE REVIEW

File: src/main/java/edu/uco/cs/v2c/desktop/linux/command/CommandParser.java [hunk 1]
```diff
@@ -29,23 +29,23 @@ public CommandParser(ConfigurationData configurationData) {
...
-      } else if (foundMacro != null) {
+      } else if (foundMacro != null && foundMacro.getEnabled()) {
         System.out.println("macro found");
         foundMacro.execute();
       } else {
         System.out.println("command/macro not found");
-        System.out.println("trying to execute anyway");
-        terminal.ExecuteCommand(targetCommand);
+        // System.out.println("trying to execute anyway");
+        // terminal.ExecuteCommand(targetCommand);
```
Comment (calebpower) [inline src/main/java/edu/uco/cs/v2c/desktop/linux/command/CommandParser.java:48]: Commenting this out was a great idea.

**Review by calebpower — APPROVED** [review]
